name = "ast1060-starter"
target = "thumbv7em-none-eabihf"
board = "ast1060-rot"
chip = "../../chips/ast1060"
stacksize = 1024 

[kernel]
name = "ast1060-starter"
requires = {flash = 20000, ram = 3072}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 4096}
start = true
stacksize = 1536
notifications = ["fault", "timer"]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

#[tasks.firmware_device_api]
#name = "firmware-device-api"
#priority = 3
#max-sizes = {flash = 8192, ram = 2048}
## uses = ["uart"]
#start = true

# [tasks.pldm_initiator]
# name = "task-pldm-initiator"
# priority = 4
# max-sizes = {flash = 4096, ram = 1024}
# start = true
# task-slots = ["firmware_device_api"]

[tasks.pldm_responder]
name = "task-pldm-responder"
priority = 4
max-sizes = { flash = 12288, ram = 8192 }
stacksize = 4352
start = true
#task-slots = ["firmware_device_api"]
